use review_me;

CREATE TABLE IF NOT EXISTS `product` (
	`id` BIGINT(10) NOT NULL AUTO_INCREMENT,
	`prod_Name` VARCHAR(30) NULL DEFAULT NULL,
	`description` VARCHAR(50) NULL DEFAULT NULL,
	`parent_product_id` BIGINT(10) NULL DEFAULT NULL,
	`created_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`),
	CONSTRAINT `FK_MANAGER` FOREIGN KEY (`parent_product_id`) REFERENCES `product` (`id`)
);

CREATE TABLE IF NOT EXISTS `review` (
	`review_id` BIGINT(10) NOT NULL AUTO_INCREMENT,
	`description` VARCHAR(50) NULL DEFAULT NULL,
	`product_id` BIGINT(10) NULL DEFAULT NULL,
	`posted_date` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`posted_by` BIGINT(10) NULL DEFAULT NULL,
	PRIMARY KEY (`review_id`),
	CONSTRAINT `Review_FK_MANAGER` FOREIGN KEY (`product_id`) REFERENCES `product` (`id`)
);

CREATE TABLE IF NOT EXISTS `User` (
	`user_id` BIGINT(10) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(40) NULL DEFAULT NULL,
	`created_on` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`user_id`)
);